OPENAI_API_KEY = "4c4927a7c697459ea5896bbed6f4d84a"

[connections.snowflake]
user="cpandya@conga.com"
authenticator="externalbrowser"
account="apttus"
warehouse="APTTUS_ADMIN"
database="APTTUS_DW"
schema="SF_PRODUCTION"